In [28]:
import pulp as pl
import numpy as np

In [9]:
# problem 4_2
prob = pl.LpProblem("day3_exercise_4_2", pl.LpMaximize)

x_1 = pl.LpVariable("x_1", lowBound=0)
x_2 = pl.LpVariable("x_2", lowBound=0)
x_3 = pl.LpVariable("x_3", lowBound=0)

prob += x_1 + x_2 + x_3

prob += 2*x_1 + x_2 + 2*x_3 <= 3
prob += 4*x_1 + 2*x_2 + x_3 <= 2

prob.solve()

print(f"{pl.LpStatus[prob.status]} solution:")
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Objective = ", pl.value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.10 
Build Date: Sep 26 2023 

command line - /usr/local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/arm64/cbc /tmp/ddc3e9f63d8944d5b803ebabd4f836eb-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /tmp/ddc3e9f63d8944d5b803ebabd4f836eb-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 17 RHS
At line 20 BOUNDS
At line 21 ENDATA
Problem MODEL has 2 rows, 3 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 2 (0) rows, 3 (0) columns and 6 (0) elements
0  Obj -0 Dual inf 3.9999997 (3)
0  Obj -0 Dual inf 3.9999997 (3)
2  Obj 1.6666667
Optimal - objective value 1.6666667
Optimal objective 1.666666667 - 2 iterations time 0.002
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Optimal solution:
x_1 = 0.0
x_2 = 0.33333333
x_3 = 1.3

In [27]:
#problem 4_2 (dual)
prob = pl.LpProblem("day3_exercise_4_2_dual", pl.LpMinimize)

y_1 = pl.LpVariable("y_1", lowBound=0)
y_2 = pl.LpVariable("y_2", lowBound=0)

prob += 3*y_1 + 2*y_2

prob += 2*y_1 + 4*y_2 >= 1
prob += y_1 + 2*y_2 >= 1
prob += 2*y_1 + y_2 >= 1

prob.solve()

print(f"{pl.LpStatus[prob.status]} solution:")
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Objective = ", pl.value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.10 
Build Date: Sep 26 2023 

command line - /usr/local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/arm64/cbc /tmp/36b14479a7ff445e954020cfef2027b2-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/36b14479a7ff445e954020cfef2027b2-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 17 RHS
At line 21 BOUNDS
At line 22 ENDATA
Problem MODEL has 3 rows, 2 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 3 (0) rows, 2 (0) columns and 6 (0) elements
0  Obj 0 Primal inf 1.2499997 (3)
2  Obj 1.6666667
Optimal - objective value 1.6666667
Optimal objective 1.666666667 - 2 iterations time 0.002
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Optimal solution:
y_1 = 0.33333333
y_2 = 0.33333333
Objective =  1.6666666499999998


In [8]:
prob = pl.LpProblem('day3_exercise_5_2_1', pl.LpMaximize)

x_1 = pl.LpVariable("x_1", lowBound=0)
x_2 = pl.LpVariable("x_2", lowBound=0)

prob += 4*x_1 + 5*x_2

prob += 14*x_1 + 11*x_2  <= 154
prob += 7*x_1 + 16*x_2 <= 112

prob.solve()

print(f"{pl.LpStatus[prob.status]} solution:")
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Objective = ", pl.value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.10 
Build Date: Sep 26 2023 

command line - /usr/local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/arm64/cbc /tmp/4b45ffc1e2204fffb76896e1837c616b-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /tmp/4b45ffc1e2204fffb76896e1837c616b-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 14 RHS
At line 17 BOUNDS
At line 18 ENDATA
Problem MODEL has 2 rows, 2 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 2 (0) rows, 2 (0) columns and 4 (0) elements
0  Obj -0 Dual inf 8.9999998 (2)
0  Obj -0 Dual inf 8.9999998 (2)
2  Obj 50.190476
Optimal - objective value 50.190476
Optimal objective 50.19047619 - 2 iterations time 0.002
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Optimal solution:
x_1 = 8.3809524
x_2 = 3.3333333
Obje

In [15]:
c_b = np.array([4, 5])
B = np.array([[14, 11], [7, 16]])
N = np.array([[1, 0], [0, 1]])
c_b @ np.linalg.inv(B) @ N

array([0.19727891, 0.17687075])

In [20]:
c_b = np.array([4, 5])
B_prime = np.array([[16/147, -11/147], [-1/21, 2/21]])
N = np.array([[1, 0], [0, 1]])
c_b @ B_prime

array([0.19727891, 0.17687075])

In [38]:
(4*16*11+7*5*10)

1054

In [22]:
16*11/21

8.380952380952381

In [23]:
prob = pl.LpProblem('day3_exercise_5_2_2', pl.LpMaximize)

x_1 = pl.LpVariable("x_1", lowBound=0)
x_2 = pl.LpVariable("x_2", lowBound=0)

prob += 4*x_1 + 5*x_2

prob += 2*x_1 + x_2  <= 6
prob += x_1 + x_2  <= 4
prob += x_1 + 2*x_2 <= 6

prob.solve()

print(f"{pl.LpStatus[prob.status]} solution:")
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Objective = ", pl.value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.10 
Build Date: Sep 26 2023 

command line - /usr/local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/arm64/cbc /tmp/4955f7735eaf418abe675cdb7aa6bd19-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /tmp/4955f7735eaf418abe675cdb7aa6bd19-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 17 RHS
At line 21 BOUNDS
At line 22 ENDATA
Problem MODEL has 3 rows, 2 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 3 (0) rows, 2 (0) columns and 6 (0) elements
0  Obj -0 Dual inf 8.9999998 (2)
0  Obj -0 Dual inf 8.9999998 (2)
2  Obj 18
Optimal - objective value 18
Optimal objective 18 - 2 iterations time 0.002
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Optimal solution:
x_1 = 2.0
x_2 = 2.0
Objective =  18.0


In [41]:
c_b = np.array([4, 0, 5])
B = np.array([[2, 0, -1], [-1, 1, -1], [-1, 0, 2]])
b = np.array([6, 4, 6]).T
1/3 * c_b * np.linalg.inv(B) @ b

array([ 8.66666667, 18.        ,  9.33333333])

In [29]:
# original
prob = pl.LpProblem('day3_exercise_original', pl.LpMaximize)

x_1 = pl.LpVariable("x_1", lowBound=0)
x_2 = pl.LpVariable("x_2", lowBound=0)

prob += x_1 + 2*x_2

prob += -2*x_1 + x_2  <= 2
prob += x_1 + x_2  <= 3

prob.solve()

print(f"{pl.LpStatus[prob.status]} solution:")
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Objective = ", pl.value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.10 
Build Date: Sep 26 2023 

command line - /usr/local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/arm64/cbc /tmp/ed39b07afe5347d7be7d6a045ba0f7db-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /tmp/ed39b07afe5347d7be7d6a045ba0f7db-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 14 RHS
At line 17 BOUNDS
At line 18 ENDATA
Problem MODEL has 2 rows, 2 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 0 (-2) rows, 0 (-2) columns and 0 (-4) elements
Empty problem - 0 rows, 0 columns and 0 elements
Optimal - objective value 5.6666667
After Postsolve, objective 5.6666667, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective 5.666666667 - 0 iterations time 0.002, Presolve 0.00
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):  

In [33]:
# original
prob = pl.LpProblem('day3_exercise_original_dual', pl.LpMinimize)

x_1 = pl.LpVariable("x_1", lowBound=0)
x_2 = pl.LpVariable("x_2", lowBound=0)

prob += 2*x_1 + 3*x_2

prob += -2*x_1 + x_2  >= 1
prob += x_1 + x_2  >= 2

prob.solve()

print(f"{pl.LpStatus[prob.status]} solution:")
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Objective = ", pl.value(prob.objective))

Welcome to the CBC MILP Solver 
Version: 2.10.10 
Build Date: Sep 26 2023 

command line - /usr/local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/arm64/cbc /tmp/b417c318b2974306a4f7d1a9231408e2-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/b417c318b2974306a4f7d1a9231408e2-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 14 RHS
At line 17 BOUNDS
At line 18 ENDATA
Problem MODEL has 2 rows, 2 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 2 (0) rows, 2 (0) columns and 4 (0) elements
0  Obj 0 Primal inf 2.9999998 (2)
2  Obj 5.6666667
Optimal - objective value 5.6666667
Optimal objective 5.666666667 - 2 iterations time 0.002
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Optimal solution:
x_1 = 0.33333333
x_2 = 1.6666667
Objective =  5.666666759999999
